author = Sven Schreiber and Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2025-01-01
description = GMM system estimation
tags = C22
min-version = 2024b
public = gmmsys gmmsys_print
data-requirement = needs-time-series-data
help = gmmsys_help.md
sample-script = gmmsys_sample.inp
#gui-main = season_plot_gui
#label = Season Plot
#menu-attachment = MAINWIN/View/GraphVars
